fund_families = [
    "HDFC Mutual Fund",
    "SBI Mutual Fund",
    "ICICI Prudential Mutual Fund",
    "Axis Mutual Fund",
    "Nippon India Mutual Fund",
    "Kotak Mutual Fund",
    "Aditya Birla Sun Life Mutual Fund",
    "UTI Mutual Fund",
    "Mirae Asset Mutual Fund",
    "Tata Mutual Fund",
    "DSP Mutual Fund",
    "IDFC Mutual Fund",
    "L&T Mutual Fund",
    "Franklin Templeton Mutual Fund",
    "Motilal Oswal Mutual Fund",
    "Parag Parikh Mutual Fund",
    "Sundaram Mutual Fund",
    "Canara Robeco Mutual Fund",
    "Mahindra Manulife Mutual Fund",
]
